package com.feiqn.gempires.models;

public enum Formation {
    ONE_CENTER,
    TWO_IN_FRONT,
    TWO_IN_BACK,
    TWO_STAGGERED_LEFT,
    TWO_STAGGERED_RIGHT,
    THREE_IN_FRONT,
    THREE_ASCENDING,
    THREE_DESCENDING,
    FOUR_WITH_BACK_SIDE_FLANKS,
    FOUR_WITH_FRONT_SIDE_FLANKS,
    FOUR_N_SHAPE,
    FOUR_REVERSE_N_SHAPE,
    FOUR_IN_FRONT,
    FIVE_ASCENDING,
    FIVE_DESCENDING,
    FIVE_W_SHAPE,
    FIVE_M_SHAPE,
    FIVE_PROTECTING_CENTER
}
