package com.feiqn.gempires.logic.items;

public enum ItemList {
    // UPGRADE ITEMS
    THYME, // Thyme is money.
    BASIL,
    MINT,
    PARSLEY,
    SAGE,
    SAFFRON,
    PURE_GEM, // "Premium currency"

    OAK_LOGS,
    WILLOW_LOGS,
    MAPLE_LOGS,
    TEAK_LOGS,
    YEW_LOGS,
    MAHOGANY_LOGS,
    MAGIC_LOGS,
    REDWOOD_LOGS,
    BLESSED_LOGS,

    COPPER_CHUNK,
    TIN_CHUNK,
    STEEL_CHUNK,
    MITHRIL_CHUNK,
    ADAMANT_CHUNK,
    RUNEITE_CHUNK,
    OBSIDIAN_CHUNK,
    CRYSTAL_CHUNK,
    BLESSED_CHUNK,

    BATTERED_RELIC,
    ORAL_HISTORY,
    TRANSCRIBED_TEACHINGS,
    BURNT_BOOK,
    ANCIENT_DIARY,
    CAVE_RELIEF,
    FOREBODING_TOME,
    HORRIFIC_TRUTH,
    COSMIC_SECRET,

    // ASCENSION ITEMS
    // 1*
    WORK_CLOTHES,
    TOOLS,

    // 2*
    LEATHER_ARMOR,
    IRON_WEAPONS,
    COLDSTONE,
    EMBERSTONE,
    LUCKY_CLOVER,
    FLINT,
    COPPER_WIRE,
    BROKEN_PROMISE,

    // 3*
    PLATE_ARMOR,
    REINFORCED_WEAPONS,
    NEVERMELT_ICE,
    LAVACOAL,
    ANGELFRUIT,
    TITANITE,
    GROUNDING_POLE,
    LAMENTING_POEM,

    // 4*
    DAMASCUS_ARMOR,
    RUNEITE_WEAPONS,
    HOLY_WATER,
    HOLY_INCENSE_ASH,
    REDWOOD_SEED,
    OBSIDIAN_GEODE,
    LIGHTNING_ROD,
    MARTYRS_DIARY,

    // 5*
    BLESSED_ARMOR,
    BLESSED_WEAPONS,
    GODDESS_TEARS,
    VOLCANO_HEART,
    REDWOOD_ROOTS,
    TITAN_FOSSIL,
    STORMS_EYE,
    NIGHTMARE_DRAWING,

    // BATTLE ITEMS:
    TORNADO,

    HEALTH_POTION_SMALL,
    HEALTH_POTION_MEDIUM,
    HEALTH_POTION_LARGE,
    HEALTH_POTION_MASSIVE,
    HEALTH_POTION_PURE,

    REVIVE_POTION,

    MANA_POTION_SMALL,
    MANA_POTION_MEDIUM,
    MANA_POTION_LARGE,
    MANA_POTION_MASSIVE,
    MANA_POTION_PURE,

}
